AdmissionApplication/urls.py
from django.urls import path
from .views import *

appname='admissionapplication'
urlpatterns = [
    path('menu_test/', MenuView, name='menu'),
    path('edit_result/', EditResultView, name='edit_result'),
    path('delete_result/', DeleteResultView, name='delete_result'),
    path('admission/', UserAddView.as_view(), name='admission'),
    path('result/<メールアドレス>/<申請番号>/', ResultView, name='result'),
    
    path('user_list', UserList.as_view(), name='list'),
    path('<int:pk>/show', UserShowWithIDView.as_view(), name='showwithID'),
    path('<int:pk>/userstatusChange', UserStatusChange, name='UserStatusChange'),
    path('<int:pk>/userrejectChange', UserRejejctChange, name='UserRejectChange'),
    
    path('entrance',UserEntrance.as_view(),name='entrance'),
    path('<int:pk>/entrance',UserEntranceWithIDView.as_view(),name='entrancewithID'),
    
    path('schedule', UserScheduleList.as_view(), name='schedulelist'),

    path('changedelete',UserChangeDeleteView.as_view(),name='changedelete'),
    path('<int:pk>/change',UserChangeWithIDView.as_view(),name='changewithID'),
    path('<int:pk>/changedeleteshow',UserChangeDeleteShowWithIDView.as_view(),name='changedeleteshowwithID'),
    path('<int:pk>/delete',UserDeleteWithIDView.as_view(),name='deletewithID'),
    ]

Team5/urls.py
from django.contrib import admin
from django.urls import path, include
import AdmissionApplication.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admissionapplication/',include('AdmissionApplication.urls'),name='admissionapplication')
]

AdmissionApplication/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.core.validators import MinLengthValidator
# Create your models here.

class User(models.Model):
    #氏名
    user_name = models.CharField('氏名',max_length=20)
    #組織名
    organization_name = models.CharField('組織名',max_length=20)       
    #電話番号
    phone_number = models.CharField('電話番号',max_length=13, validators=[MinLengthValidator(12)])
    #メールアドレス
    mail_address = models.CharField('メールアドレス',max_length=255)
    #入館予定
    entrance_schedule = models.DateTimeField('入館予定日時',blank=False,null=False)
    #entrance_schedule = models.DateTimeField('入館予定日時',blank=True,null=True)      
    #退館予定
    exit_schedule = models.DateTimeField('退館予定日時',blank=False,null=False)
    #exit_schedule = models.DateTimeField('退館予定日時',blank=True,null=True)

    #入館目的
    purpose_of_admission = models.TextField('入館目的',max_length=100) 
    #申請時間
    application_date = models.DateTimeField('申請時間',default=timezone.now, blank=True,null=True)
    
    #入館申請番号
    application_number = models.PositiveIntegerField('入館申請番号')
    #ワンタイムパスワード
    password = models.CharField('パスワード',max_length=8, null=False)      
    #承認可否
    approval = models.BooleanField('承認可否',default=False)
    #入館実績
    achivement_entrance = models.DateTimeField('入館実績日時',blank=True,null=True)      
    #退館実績
    achivement_exit = models.DateTimeField('退館実績日時',blank=True,null=True) 

    def __str__(self):
        return self.user_name   
      
    def get_absolute_url(self):
        return reverse("result", kwargs={
            'メールアドレス': self.mail_address,
            '申請番号': self.application_number
            })

AdmissionApplication/forms.py
from django import forms
from .models import User
from pip._vendor.pkg_resources import require
from django.contrib.admin import widgets
from django.forms.widgets import DateTimeInput


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["user_name", "organization_name", "phone_number", "mail_address", "entrance_schedule", "exit_schedule", "purpose_of_admission"]
        
        
class UserEntranceLogin(forms.Form):
    application_number=forms.IntegerField(label='入館申請番号')
    #application_number=forms.IntegerField(label='入館申請番号',required=True)
class UserEntranceForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["application_number",]
class UserChangeDeleteForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["application_number","password"]
        widgets={"password":forms.PasswordInput()}

                       
class UserPasswordForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["password"]
        widgets={"password":forms.PasswordInput()}
    
class UserIdForm(forms.Form):
    user_id = forms.IntegerField(label='ID')    

AdmissionApplication/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView
from .models import User
from .forms import *
from django.views.generic.base import TemplateView
from django.utils import timezone
from django.views.generic import ListView
from django.shortcuts import get_object_or_404
from django.core.mail import send_mail, EmailMessage
from django.template.loader import get_template
from django.shortcuts import redirect
import re, string, random
from datetime import date, datetime
from django.db import models
from Team5.wsgi import application
from django.contrib.admin.utils import lookup_field
from unicodedata import lookup
from django.contrib import messages
from django.db.models import Q
from django.contrib import messages 
# Create your views here.

phone_regex = re.compile(r'''(
    (0)
    (\d{1,3})
    (-)
    (\d{1,4})
    (-)
    (\d{3,4})
    )''', re.VERBOSE)

def MenuView(request):
    return render(request, 'AdmissionApplication/menu.html')

class UserAddView(CreateView):
    model = User
    #fields = ("user_name", "organization_name", "phone_number", "mail_address", "entrance_schedule", "exit_schedule", "purpose_of_admission", "password")
    form_class = ApplicationForm
    template_name = 'AdmissionApplication/admission.html'
    #success_url = '../menu_test'


    def form_valid(self, form):
        ctx = {'form': form}
        if form.is_valid():
            word = string.digits + string.ascii_lowercase + string.ascii_uppercase
            user = form.save(commit=False)
            random_number=random.randrange(999) + int(datetime.now().strftime('%y')) * 100000 + int(datetime.now().strftime('%m')) * 1000
            while(User.objects.filter(application_number__exact=random_number).count() > 0):
                random_number = random.randrange(999) + int(datetime.now().strftime('%y')) * 100000 + int(datetime.now().strftime('%m')) * 1000
            user.application_number = random_number
            user.password = ''.join([random.choice(word) for i in range(8)])
            
        if self.request.POST.get('next', '') == 'confirm':
            form_user_name = self.request.POST.get("user_name")
            form_organization_name = self.request.POST.get("organization_name")
            form_phone_number = self.request.POST.get("phone_number")
            form_mail_address  = self.request.POST.get("mail_address")
            form_entrance_schedule = self.request.POST.get("entrance_schedule")
            form_exit_schedule = self.request.POST.get("exit_schedule")
            phone_serch = re.search(phone_regex, form_phone_number)
            check = True
            #承認済み利用者を取得
            all_entries = User.objects.filter(approval__exact="True")
            #氏名と異なる利用者を取得
            all_entries = all_entries.exclude(user_name=form_user_name)
            #組織名と異なる利用者を取得
            all_entries = all_entries.exclude(organization_name=form_organization_name)
            #自分の入館時間<他の利用者の退館時間<自分の退館時間
            
            overlapping_1 = all_entries.filter(exit_schedule__range=(form_entrance_schedule, form_exit_schedule))
            #自分の入館時間<他の利用者の入館時間<自分の退館時間
            overlapping_2 = all_entries.filter(entrance_schedule__range=(form_entrance_schedule, form_exit_schedule))
            #他の利用者の入館時間<自分の入館時間<自分の退館時間<他の利用者の退館時間
            overlapping_3 = all_entries.filter(entrance_schedule__lt=form_entrance_schedule)
            overlapping_3 = overlapping_3.filter(exit_schedule__gt=form_exit_schedule)

            today = datetime.now().strftime('%Y-%m-%d %H:%M')
           
            if (re.match('[ｦ-ﾟ]', form_user_name) != None):
                messages.error(self.request, '氏名に半角カナは使用できません.')
                check = False
            if 'None' in str(phone_serch):
                messages.error(self.request, '有効な電話番号を入力してください．')
                check = False           
            if (re.match('[A-Za-z0-9\._+]+@[A-Za-z]+\.[A-Za-z]', form_mail_address) == None) :
                messages.error(self.request, '有効なメールアドレスを入力してください.')
                check = False      
            if form_entrance_schedule > form_exit_schedule:
                messages.error(self.request, '入館予定日時が退館予定日時より前になっています．')
                check = False
            if form_entrance_schedule < today:
                messages.error(self.request, '入館予定日時が現在時刻より前になっています.')
                check = False
            if overlapping_1.count() > 0 or overlapping_2.count() > 0 or overlapping_3.count() > 0:
                messages.error(self.request, '他の利用者の方と予定日時が重複しています.')
                check = False
            if check:
                return render(self.request, 'AdmissionApplication/confirm.html', ctx)
            else:
                return render(self.request, 'AdmissionApplication/admission.html', ctx)
            
        if self.request.POST.get('next', '') == 'back':
            return render(self.request, 'AdmissionApplication/admission.html', ctx)      
         
        if self.request.POST.get('next', '') == 'create':
            user = form.save(commit=False)
            template = get_template('AdmissionApplication/mail/create_mail.html')
            mail_ctx={
                'user_name': form.cleaned_data['user_name'],
                'organization_name': form.cleaned_data['organization_name'],
                'phone_number': form.cleaned_data['phone_number'],
                'mail_address': form.cleaned_data['mail_address'],
                'entrance_schedule': form.cleaned_data['entrance_schedule'],
                'exit_schedule': form.cleaned_data['exit_schedule'],
                'purpose_of_admission': form.cleaned_data['purpose_of_admission'],
                'application_number': user.application_number,
                'password': user.password,
                }
            EmailMessage(
                subject='入館申請完了',
                body=template.render(mail_ctx),
                to=[form.cleaned_data['mail_address']],
#                cc=[],
                bcc=['team05.m46@gmail.com'],
            ).send()
            return super().form_valid(form)
                
def ResultView(request, **kwargs):
    return render(request, 'AdmissionApplication/result.html',{
        'contents': kwargs,
    })

class UserList(ListView):
    model = User

    def post(self, request, *args, **kwargs):
        user_id = self.request.POST.get('user_id')
        user = get_object_or_404(User, pk=user_id)
        user.save()
        return HttpResponseRedirect(reverse('list')).order_by('-entrance_schedule')
    
    def get_queryset(self):
        q_word = self.request.GET.get('query')
 
        if q_word:
            object_list = User.objects.filter(
                Q(organization_name__icontains=q_word))
        else:
            object_list = User.objects.all()
        return object_list 
    
class UserEntrance(TemplateView):    
    model=User
    fields = ("application_numbrer",)
    template_name = 'AdmissionApplication/entrance.html'
    form_class = UserEntranceForm
    def post(self, request, *args, **kwargs):
        application_number = self.request.POST.get("application_number")
        s=False
        who=False
        for a in User.objects.values_list("application_number",flat=True ):
            user = get_object_or_404(User, application_number=a)  
            pk=user.pk 
            #他に誰か入っている人がいるか
            if user.achivement_entrance and user.achivement_exit is None and not int(application_number)==int(a):
                who=True
                
            #入力された入館申請番号があるか
            if int(a)==int(application_number):
                s=True     
        if s==True :
            user = get_object_or_404(User, application_number=application_number)
            entrance_time=user.entrance_schedule
            exit_time=user.exit_schedule
            approval=user.approval
            time=timezone.now()
            if user.achivement_entrance and user.achivement_exit:
                messages.info(self.request, '既に入退館済みです.')
                return HttpResponseRedirect(reverse('entrance'))
            elif approval==True and time>entrance_time and time>exit_time and user.achivement_entrance==None:
                messages.info(self.request, '入館申請出来る時間が過ぎています.')
                return HttpResponseRedirect(reverse('entrance'))
            elif who==True and approval==True and time>entrance_time :
                messages.info(self.request, '現在まだ入っている方がいらっしゃいます.')
                return HttpResponseRedirect(reverse('entrance'))
            elif approval==True and time>entrance_time:
                user = get_object_or_404(User, application_number=application_number)  
                pk=user.pk 
                return HttpResponseRedirect(reverse('entrancewithID', kwargs={'pk':pk}))
            elif approval==True :
                messages.info(self.request, '入館申請出来る時間ではありません.')
                return HttpResponseRedirect(reverse('entrance'))
            else :
                messages.info(self.request, '承認されていません.')
                return HttpResponseRedirect(reverse('entrance'))
        else :
            messages.info(self.request, '入館申請番号が間違っています.')
            return HttpResponseRedirect(reverse('entrance'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = UserEntranceForm()
        return context    

      
class UserEntranceWithIDView(UpdateView):
    model = User
    fields = ("user_name", "organization_name", "phone_number", "mail_address", "entrance_schedule", "exit_schedule", "purpose_of_admission","application_number")
    template_name = 'AdmissionApplication/entrancewithID.html'
    def post(self, request, *args, **kwargs):
        if self.request.POST.get('next', '') == 'entrance_time_save':
            application_number = kwargs.get('pk')

AdmissionApplication/templates/AdmissionApplication/changeconfirm.html
{% block title %} add {% endblock %}
{% block content %}
              <div class="header"><h3>入館情報修正</h3></div>
                <p>修正内容を確認してください</p>
                <table>
                    <tr><td>氏名</td><td>{{form.user_name.value}}</td></tr>
                    <tr><td>組織名</td><td>{{form.organization_name.value}}</td></tr>
                    <tr><td>電話番号</td><td>{{form.phone_number.value}}</td></tr>
                    <tr><td>メールアドレス</td><td>{{form.mail_address.value}}</td></tr>
                	<tr><td>入館予定</td><td>{{form.entrance_schedule.value}}</td></tr>
                    <tr><td>退館予定</td><td>{{form.exit_schedule.value}}</td></tr>
                    <tr><td>入館目的</td><td>{{form.purpose_of_admission.value}}</td></tr>
                </table>
                <form class="ui form" action="{% url 'changewithID' user.id %}" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                        {{field.as_hidden}}
                    {% endfor %}
                     <button onClick="javascript:history.go(-1);">戻る</button>
<!--
<button class="ui button grey" type="submit" name="next" value="back_change">戻る</button>
-->

                    <button class="ui button orange" type="submit" name="next" value="change">修正</button>
                </form>

</div>
{% endblock %}

AdmissionApplication/templates/AdmissionApplication/changedelete.html
{% extends "base.html" %}

{% block title %} 入館申請番号入力画面 {% endblock %}

{% block main %}
<!--
<a href="{{request.META.HTTP_REFERER}}">戻る</a>
 -->

<form class="ui form" action="{% url 'changedelete' %}" method="post">
{% csrf_token %}
{{ form }}
<button class="btn btn-outline-primary" type="submit" >確認</button>
<!--
<button type="submit" class="btn btn-primary">確認</botton> 
<input type="submit"/>
-->
</form>
{% if messages %}
{% for message in messages %}
 		<p><font color ="red"> {{message}} </font></p>
 		{% endfor %}
{% endif %}
</form>

{% endblock %} 

AdmissionApplication/templates/AdmissionApplication/changedeleteshowwithID.html
{% extends "base.html" %}

{% block title %} 入館情報確認画面 {% endblock %}

{% block main %}

<ul>
 <form  method="post">
 {% csrf_token %}
<input type = "hidden" name = "application_number" value={{application_number}} required id="id_application_number">
<!--
 <a href="{{request.META.HTTP_REFERER}}">戻る</a>
-->
<dl>
<dt>入館申請番号</dt><dd>{{ user.application_number }}</dd>
<dt>名前</dt><dd>{{ user.user_name }}</dd>
<dt>組織名</dt><dd>{{ user.organization_name }}</dd>
<dt>電話</dt><dd>{{ user.phone_number }}</dd>
<dt>メール</dt><dd>{{ user.mail_address }}</dd>
<dt>入館日時</dt><dd>{{ user.entrance_schedule }}</dd>
<dt>退館日時</dt><dd>{{ user.exit_schedule }}</dd>
<dt>入館目的</dt><dd>{{ user.purpose_of_admission }}</dd>
<dt>承認</dt><dd>
{% if user.approval == False %}未承認{% endif %}
{% if user.approval == True %}承認済み{% endif %}
</dd>
</dl>
<!--
<button class="ui button grey" type="submit" name="next" value="back">戻る</button>
<button onClick="javascript:history.go(-1);">戻る</button>
  -->
{% if not user.approval %}
<button class="ui button grey" type="submit" name="next" value="change">修正</button>
<button class="ui button orange" type="submit" name="next" value="delete">削除</button>
{% endif %}

 </form>
 
{% endblock %} 

AdmissionApplication/templates/AdmissionApplication/changewithID.html
{% extends "base.html" %}

{% block title %} 入館情報修正画面 {% endblock %}

{% block main %}

<ul>
 <form  method="post">
 {% csrf_token %}
<input type = "hidden" name = "application_number" value={{application_number}} required id="id_application_number">
<!--
<a href="{{request.META.HTTP_REFERER}}">戻る</a>
-->
<table>
{{ form.as_table }}
<script>
 $(function () {
	$.datetimepicker.setLocale("ja");
	$('#id_entrance_schedule').datetimepicker({
		format : 'Y-m-d H:i',
		step : 10
	});
	
	$('#id_exit_schedule').datetimepicker({
		format : 'Y-m-d H:i',
		step : 10
	});
	});
	</script>
</table>

<form action="" method="POST" name="form_change_choice_text" id="form_change_choice_text">
            {% csrf_token %}
           {{ password_form.non_field_errors }}
              {{ password_form.as_p }}
{% if messages %}
{% for message in messages %}
 		<p><font color ="red"> {{message}} </font></p>
 		{% endfor %}
{% endif %}                  

<!--
<button class="ui button grey" type="submit" name="next" value="back_show">戻る</button>
  <button onClick="javascript:history.go(-1);">戻る</button>
<button class="ui button orange" type="submit" name="next" value="change">修正</button>
-->
<button class="ui button grey" type="submit" name="next" value="change" onclick='return confirm("本当に修正してよろしいですか？");'>修正</button>
 </form>

 
{% endblock %} 

AdmissionApplication/templates/AdmissionApplication/confirm.html
{% extends "base.html" %} 

{% block title %} add {% endblock %}
{% block main %}
{% block content %}
	<div class="header"><h3>入館申請</h3></div>
	<p></p>
	<div class="alert alert-info" role="alert">内容を確認してください．</div>
    <table class="table table-hover">
        <tr><td>氏名</td><td>{{form.user_name.value}}</td></tr>
        <tr><td>組織名</td><td>{{form.organization_name.value}}</td></tr>
        <tr><td>電話番号</td><td>{{form.phone_number.value}}</td></tr>
        <tr><td>メールアドレス</td><td>{{form.mail_address.value}}</td></tr>
    	<tr><td>入館予定</td><td>{{form.entrance_schedule.value}}</td></tr>
        <tr><td>退館予定</td><td>{{form.exit_schedule.value}}</td></tr>
        <tr><td>入館目的</td><td>{{form.purpose_of_admission.value}}</td></tr>
    </table>
    <form class="ui form" action="{% url 'admission' %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{field.as_hidden}}
        {% endfor %}
        <button class="btn btn-outline-primary" type="submit" name="next" value="back">戻る</button>
        <button class="btn btn-outline-success" type="submit" name="next" value="create">申請</button>
    </form>

</div>
{% endblock %}
{% endblock %} 

AdmissionApplication/templates/AdmissionApplication/delete_result.html
{% extends "base.html" %}

{% block title %} 申請情報削除完了 {% endblock %}

{% block main %}
<font size="5">申請情報を削除しました.<br>
<a href="{% url 'menu' %}"><button type="button" class="btn btn-light">ホームに戻る</button></a>


{% endblock %}

AdmissionApplication/templates/AdmissionApplication/deletewithID.html
{% extends "base.html" %}

{% block title %} 削除確認画面 {% endblock %}

{% block main %}

<ul>
 <form method="post">
 {% csrf_token %}
<input type = "hidden" name = "application_number" value={{application_number}} required id="id_application_number">

<!--
<a href="{{request.META.HTTP_REFERER}}">戻る</a>
 -->
 <dl>
<dt>入館申請番号</dt><dd>{{ user.application_number }}</dd>
<dt>名前</dt><dd>{{ user.user_name }}</dd>
<dt>組織名</dt><dd>{{ user.organization_name }}</dd>
<dt>電話</dt><dd>{{ user.phone_number }}</dd>
<dt>メール</dt><dd>{{ user.mail_address }}</dd>
<dt>入館日時</dt><dd>{{ user.entrance_schedule }}</dd>
<dt>退館日時</dt><dd>{{ user.exit_schedule }}</dd>
<dt>入館目的</dt><dd>{{ user.purpose_of_admission }}</dd>
</dl>
 <table>
{{ form.as_table }}
</table>
{% if messages %}
{% for message in messages %}
 		<p><font color ="red"> {{message}} </font></p>
 		{% endfor %}
{% endif %}
 
<!--
<button class="ui button grey" type="submit" name="next" value="back">戻る</button>
-->
 <button onClick="javascript:history.go(-1);">戻る</button>
<button class="ui button grey" type="submit" name="next" value="delete" onclick='return confirm("本当に削除してよろしいですか？");'>削除</button>

 
 </form>
 
{% endblock %} 

AdmissionApplication/templates/AdmissionApplication/edit_result.html
{% extends "base.html" %}

{% block title %} 申請情報修正完了 {% endblock %}

{% block main %}
<font size="5">申請情報が修正されました.<br>
<a href="{% url 'menu' %}"><button type="button" class="btn btn-light">ホームに戻る</button></a>


{% endblock %}

AdmissionApplication/templates/AdmissionApplication/entrancewithID.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>入館情報確認画面</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'bootstrap/css/original_style.css' %}">
</head>
<body>
<div class="container">
	<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
	  <a href="#" class="navbar-brand">データセンター</a>

	  <div class="collapse navbar-collapse" id="navmenu2a">
	    <div class="navbar-nav">
	      <a class="nav-item nav-link" href="{% url 'admission' %}">入館申請</a>
	      <a class="nav-item nav-link" href="{% url 'admission' %}">修正・削除</a>
	      <a class="nav-item nav-link" href="{% url 'entrance' %}">入館・退館</a>
	    </div>
	  </div>
	</nav>
	<br />
	
	<form  method="post">
	{% csrf_token %}
	<input type = "hidden" name = "application_number" value={{application_number}} required id="id_application_number">	
	<table class="table table-hover">
		<tr>
			<td>組織名</td>
			<td>{{ user.organization_name }}</td>
		</tr>
		<tr>
			<td>氏名</td>
			<td>{{ user.user_name }}</td>
		</tr>
		<tr>
			<td>電話番号</td>
			<td>{{ user.phone_number }}</td>
		</tr>
		<tr>
			<td>メールアドレス</td>
			<td>{{ user.mail_address }}</td>
		</tr>
		<tr>
			<td>入館予定日時</td>
			<td>{{ user.entrance_schedule }}</td>
		</tr>
		<tr>
			<td>退館予定日時</td>
			<td>{{ user.exit_schedule }}</td>
		</tr>
		<tr>
			<td>入館目的</td><td>{{ user.purpose_of_admission }}</td>
		</tr>
	</table>
	<table class="table table-borderless">
	<tr>
	{% if user.achivement_entrance %}
		<td><button type="button" class="btn btn-outline-success" disabled>入館</botton></td>
    {% else %}		
		<td><button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#testModal">入館</button></td>
	{% endif %}

	{% if user.achivement_exit %}
		<td><button type="button" class="btn btn-outline-primary" disabled>退館</botton></td>
	{% elif user.achivement_entrance  %}
		<td><button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#testModal2">退館</button></td>
	{% else %}	
		<td><button type="button" class="btn btn-outline-primary"disabled >退館</botton></td>
	{% endif %}
		<td><button type="submit" class="btn btn-outline-secondary">戻る</button></td>
	</tr>
	</table>       	
	<div class="modal fade" id="testModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4><div class="modal-title" id="myModalLabel">入館確認</div></h4>
				</div>
				<div class="modal-body">
					<label>入館しますか？</label>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-light" data-dismiss="modal">閉じる</button>
					<button class="btn btn-outline-success" type="submit" name="next" value="entrance_time_save">入館</button>
				                
				</div>
			</div>
		</div>
	</div>	
	<div class="modal fade" id="testModal2" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
	    <div class="modal-dialog">
	        <div class="modal-content">
	            <div class="modal-header">
	                <h4><div class="modal-title" id="myModalLabel">退館確認</div></h4>
	            </div>
	            <div class="modal-body">
	                <label>退館しますか？</label>
	            </div>
	            <div class="modal-footer">
	                <button type="button" class="btn btn-light" data-dismiss="modal">閉じる</button>
	            	  <button class="btn btn-outline-primary" type="submit" name="next" value="exit_time_save">退館</button>
	                
	            </div>
	        </div>
	    </div>
	</div>
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	</form>

 
</div>
</body>
</html>